name: Follow-On Tests
on:
  workflow_run:
    workflows: ["Sleep Test Workflow"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Run Go script
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          GITHUB_SHA: ${{ github.event.workflow_run.head_sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run main.go
