name: Follow-On Tests
on:
  workflow_run:
    workflows: ["Sleep Test Workflow"]
    types:
      - completed
jobs:
  test-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: echo "The follow-on works!!"
      - name: Update PR status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              name: 'Follow-On Test Status',
              head_sha: '${{ github.event.workflow_run.head_sha }}',
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Follow-On Test Results',
                summary: 'The follow-on tests completed successfully'
              }
            })
