name: Sleep Test Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  sleep-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Log the time
        run: date
